# Generated by Django 3.0.1 on 2020-02-06 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('eventType', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.type')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
