# Generated by Django 3.0.1 on 2020-02-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200207_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='events.type'),
        ),
    ]
