version: '3'
    
services:
  db:
    image: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
        - "3306:3306"
    volumes:
        - db-data:/foo
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes: 
    db-data: