"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import threading
import time
from datetime import timedelta
from os import path

import django_heroku
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

if os.path.exists("./mysite/key.txt"):
    SECRET_KEY_FILE = open("./mysite/key.txt", "r")
    SECRET_KEY = SECRET_KEY_FILE.read()
    SECRET_KEY_FILE.close()
else:
    SECRET_KEY = get_random_secret_key()
    SECRET_KEY_FILE = open("./mysite/key.txt", "w+")
    SECRET_KEY_FILE.write(SECRET_KEY)
    SECRET_KEY_FILE.close()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CREATE_DEBUG_USERS = True

# Don't remove this if
if not DEBUG:
    CREATE_DEBUG_USERS = False
    SECURE_SSL_REDIRECT = True

ALLOWED_HOSTS = ['csssinf.herokuapp.com']


# Application definition
INSTALLED_APPS = ['django.contrib.admin',
                  'django.contrib.auth',
                  'django.contrib.contenttypes',
                  'django.contrib.sessions',
                  'django.contrib.messages',
                  'django.contrib.staticfiles',
                  'chunked_upload',
                  'corsheaders',
                  'rest_framework',
                  'rest_framework.authtoken',
                  'fileSystem',
                  'users',
                  'timetable',
                  'events',
                  'treasurer',
                  'other']
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware',
              'django.contrib.sessions.middleware.SessionMiddleware',
              'django.middleware.common.CommonMiddleware',
              'django.contrib.auth.middleware.AuthenticationMiddleware',
              'django.contrib.messages.middleware.MessageMiddleware',
              'django.middleware.clickjacking.XFrameOptionsMiddleware',
              'corsheaders.middleware.CorsMiddleware',
              'whitenoise.middleware.WhiteNoiseMiddleware',
              'django.middleware.common.CommonMiddleware', ]
CORS_ORIGIN_WHITELIST = ["http://localhost:4200"]
ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'staticfiles')],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': ['django.template.context_processors.debug',
                               'django.template.context_processors.request',
                               'django.contrib.auth.context_processors.auth',
                               'django.contrib.messages.context_processors.messages', ],
    },
}, ]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'CSSS',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',  # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [{
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }, ]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pl-PL'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/staticfiles/'
MEDIA_URL = '/uploaded_files/'

MEDIA_ROOT = os.path.join(BASE_DIR, '/media/')
if DEBUG:
    MEDIA_ROOT = './media/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
django_heroku.settings(locals())

# Error Mesages
ERROR_MESSAGE_404={"detail": "Not found object."}
ERROR_MESSAGE_400={"detail": "Bad parameters."}
ERROR_MESSAGE_204={"detail": "Object deleted."}
ERROR_MESSAGE_201={"detail": "Objects created."}
ERROR_MESSAGE_DEL={"detail": "Encountered a problem while deleting the file."}

# Upload Settings

CHUNKED_UPLOAD_MAX_BYTES = None
CHUNKED_UPLOAD_EXPIRATION_DELTA = timedelta(hours=5)

#Google Dysk API

GOOGLE_API_CREDENTIALS = 'credentialsGoogleApi.json'