# Generated by Django 3.0.1 on 2020-02-04 10:12

from django.db import migrations, models
import django.db.models.deletion
import timetable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('start', models.TextField()),
                ('end', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('classroom', models.TextField(default='')),
                ('teacher', models.TextField(default='')),
                ('day', models.IntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY')], default=timetable.models.dayOfWeek['MONDAY'])),
                ('group', models.IntegerField(default=-1)),
                ('hour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.HourLesson')),
            ],
        ),
    ]
